### ISSUE TITLE
Make term dates configurable in the admin UI

### ISSUE THREAD

**Issue by bp323** [CUL-DigitalServices/grasshopper-ui#124]
Create configuration for the terms and make them configurable through the admin UI.

**Comment by bp323** [comment]
I'm bumping this to high priority as we'll need it in batch editing to calculate which events belong to the terms.

**Comment by Coenego** [comment]
Assigning to myself for implementation

**Comment by Coenego** [comment]
Closing as this is handled in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/131
