### ISSUE TITLE
Only show the visibility button in batch edit mode

### ISSUE THREAD

**Issue by bp323** [CUL-DigitalServices/grasshopper-ui#143]
We should only show the visibility button in batch edit mode.

Assigning to @Coenego as he did the initial work on visibility

**Comment by bp323** [comment]
Putting on hold as draft status hasn't been implemented in the backend yet.

**Comment by Coenego** [comment]
This is depending on https://github.com/CUL-DigitalServices/grasshopper-ui/pull/160

**Comment by Coenego** [comment]
Fixed in  https://github.com/CUL-DigitalServices/grasshopper-ui/pull/160
