### ISSUE TITLE
Add week number to display date in batch edit

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#145]
![screen shot 2015-02-03 at 17 24 55](https://cloud.githubusercontent.com/assets/2194396/6025348/ad1350f2-abc9-11e4-9c5e-85cf80956d56.png)

**Comment by bp323** [comment]
Sorry, I accidentally created a duplicate at https://github.com/CUL-DigitalServices/grasshopper-ui/issues/147 which has more info
