### ISSUE TITLE
Organisers shouldn't be displayed vertically

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#181]
When viewing the batch edit UI on a small resolution, the organisers are listed vertically on top of each other.

![screen shot 2015-02-23 at 10 13 54](https://cloud.githubusercontent.com/assets/2194396/6326470/d96c82a6-bb49-11e4-82b2-332a66144df6.png)

**Comment by Coenego** [comment]
Looks like there is also so design needed. Assigning to @oszkarnagy

**Comment by bp323** [comment]
Closing as this is fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/204
