### ISSUE TITLE
jQuery.min.map warning

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#184]
The following warning gets thrown in the browser:

`Denying load of chrome-extension://gkojfkhlekighikafcpjkiklfbnlmeio/js/jquery.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.`

**Comment by bp323** [comment]
I'm not getting this error, can you try disabling your extensions in Chrome and see if the problem persists?

**Comment by bp323** [comment]
Closing as this is not an app error.
