### ISSUE TITLE
Q: Missing multiple delete OT events

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#185]
I wonder if we're missing a multi-delete button/.. for OT events.

**Comment by Coenego** [comment]
Assigning to @oszkarnagy

**Comment by oszkarnagy** [comment]
Yes we left that out, but since OT events are outliers rather than norm I think it's OK, and proceed with user testing data in hand, adding as/if there is a demonstrated need.

**Comment by bp323** [comment]
Closing per comment
