### ISSUE TITLE
Adjusting a start time hour, should auto adjust the end time

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#201]
With +1 hour

**Comment by bp323** [comment]
I'm assuming this is for batch editing of dates only and the individual fields' popover works as expected?

**Comment by bp323** [comment]
Assigning to myself for implementation

**Comment by bp323** [comment]
Incorporated in https://github.com/CUL-DigitalServices/grasshopper-ui/issues/263
