### ISSUE TITLE
Number of modules should be hidden on base state

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#214]
Student UI:
When user selects a tripos / part the number of module count info is correctly displayed. However if user navigates away from that state, back to "no selection" state at the root URL, the module count is still displayed. It shouldn't. 

![my_timetable](https://cloud.githubusercontent.com/assets/117483/6410254/9d01a714-be65-11e4-816d-afb7fbc09d67.png)

**Comment by bp323** [comment]
Fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/216
