### ISSUE TITLE
Do font smoothing for typography win!

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#222]
2 CSS lines should do the trick:

```
html, html a {
-webkit-font-smoothing: antialiased;
text-shadow: 1px 1px 1px rgba(0,0,0,0.004);
}
```

**Comment by Coenego** [comment]
![screen shot 2015-02-27 at 15 07 27](https://cloud.githubusercontent.com/assets/2194396/6414812/4ee8ce4a-be92-11e4-8903-8f99867e2bd1.png)

**Comment by bp323** [comment]
This is incorporated in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/231
