### ISSUE TITLE
Initialise the calendar component with Monday as the first day

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#225]
After thinking about this for a while, I think we should put a stick in the ground and display calendars as the rest of the world: Monday first in all calendar views.

I am assuming this is a configuration option in fullCalendar, and so switching is trivial.

EDIT: Exported calendars in client apps will display the data Monday first, so consistency is on our side too.

EDIT 2: You can't put a foot in the ground, that would be awkward. Instead put a stick in the ground.

**Comment by Coenego** [comment]
![7drhiqr](https://cloud.githubusercontent.com/assets/2194396/6414502/d3e49118-be8f-11e4-8a3c-d760419cfe52.gif)

**Comment by bp323** [comment]
![](http://cdn.meme.am/instances/250x250/58914056.jpg)
It's an option in fullcalendar but that doesn't fix the issue. All views where built with the knowledge that the first day of the week would be a Thursday so we'll have to go through them and make changes.

**Comment by oszkarnagy** [comment]
"go through them": We should estimate the effort and make an emotional decision :8ball:

**Comment by bp323** [comment]
AFAIK nothing has come up in user testing to indicate that the current start of day is confusing. I'll close this issue.
