### ISSUE TITLE
Dropdown icons should be consistent

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#237]
Event type has it right I think

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6445047/92401da6-c0f9-11e4-9bc4-cd565d1d3693.png)

**Comment by bp323** [comment]
Will need to investigate whether or not it's customisable. The little arrow is part of a sprite in the plugin, we don't control it.
