### ISSUE TITLE
Drop font weight on 'Draft' display in part dropdown

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#239]
to 200:

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6445580/baac1422-c0fc-11e4-98ee-fea437f66d96.png)

**Comment by bp323** [comment]
Will need to investigate if we can customise this without rewriting the plugin

**Comment by bp323** [comment]
We don't have that much control over how the Chosen plugin renders this, anything else is probably too much work for what it is.
