### ISSUE TITLE
Drop drop shadow from tripos and part selectors

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#243]
We is flat :)

**Comment by bp323** [comment]
We'll need to come up with something else to make it stand out from the rest then. This is how it looks without drop shadow:

![screen shot 2015-03-03 at 15 19 18](https://cloud.githubusercontent.com/assets/218391/6465392/c10db9a8-c1b8-11e4-8c30-57b0f3869f35.png)

**Comment by bp323** [comment]
Assigning to @oszkarnagy for feedback

**Comment by bp323** [comment]
Incorporated in #247
