### ISSUE TITLE
Refine tripos part selection behaviour

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#252]
Starting from an event list display state, if I select a new tripos I would NOT expect to go to the home page. The behaviour should be:

From this state:
 * If a tripos is changed > the part selector is re-freshed, but event listing page stays
 * If a part is selected > We navigate to the new tripos & part combination
 * if a tripos is selected, but then user selects another module series from the list, the tripos selector should jump back to the currently selected tripos.

**Comment by bp323** [comment]
This is inconsistent to what the behaviour should be when you're loading up a URL. For example, consider this URL: `timetable.cam.ac.uk/admin?tripos=234`. When the page loads that would bring up the admin home page and give you the option to select the part from the picker or one of the editable parts on the home page. You are proposing a dirty state that can't be recreated with the URL and I think we should avoid that. Another motivation for not doing it is that the action of selecting another tripos should be sufficient to assume that the user is not interested in the current part any longer.

**Comment by oszkarnagy** [comment]
I think you make a good point. Thinking this through, I think the benefit of making this consistent with how the part selector behaviour (which does't navigate away when selected from the event listing page) si probably less than the complexity of handling that dirty state.

Happy to close this as a wont fix for now and only consider re-opening it if we see major issues in real life navigation from test participants.

Thanks for being vigilant and keeping things simple.

**Comment by bp323** [comment]
Closing per discussion. When real users see a problem we can reopen.
