### ISSUE TITLE
Bug: Remove flicker when loading a series

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#260]
Low priority:

When I select a tripos/part from the home page, the first series of the first module is loaded correctly, however during the loading flow the the main content screen goes black, then shows the home screen again then the series data is shown.

Ideally we should put in a simple loading bar for the main content page at the start of the loading sequence, and only remove it when the series data is loaded, eliminating the flicker.

**Comment by bp323** [comment]
Assigning to myself to have a look

**Comment by bp323** [comment]
Might be fixed with https://github.com/CUL-DigitalServices/grasshopper-ui/pull/292

**Comment by bp323** [comment]
Closing. I checked and this is fixed in #292 .
