### ISSUE TITLE
After creation & edit make sure we have a fresh state

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#280]
Noticed that currently we need to refresh the page when creating a module. Similarly we might need to re-fresh for a clean series view too.

For the beta I think we should make sure that we automatically fetch an up to date state after creation / (name) editing to make sure we always have an up to date left nav listing items and event listing.

**Comment by bp323** [comment]
Might be fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/292

**Comment by bp323** [comment]
Closing. This is fixed in #292
