### ISSUE TITLE
Display number of items in the current calendar view

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#294]
- [ ] Add the number of items that are displayed in the calendar (incl. the hidden ones)

![adj-remove-aggregated-pattern](https://cloud.githubusercontent.com/assets/2194396/6778407/5cffc798-d14a-11e4-9f4b-d14c8f43c789.jpg)

**Comment by Coenego** [comment]
Question for @oszkarnagy: Is the `18 items` on the bottom a link?

**Comment by bp323** [comment]
Per comment from @oszkarnagy 
`
The number of items in calendar view is the number of series you have added to your calendar. When you click it, the idea was to reset the top nav dropdowns to default and display a list of all items (series and modules) you have added to your calendar. Again this is not validated design and should be put on hold until all other core journeys are done.
`

**Comment by bp323** [comment]
Looking at the original motivation for this, not having it validated by users and having implemented the 'My agenda' view this doesn't make much sense to implement any longer. I'm going to close this issue.
