### ISSUE TITLE
Display issue with events in month view

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#302]
When the browser window is being resized vertically, the events are replaced by **+x more**. This looks a bit odd since there are no events shown initially. It rather should be **x events** or display one event and add **+x more** for the remaining events.

![screen shot 2015-03-24 at 16 09 48](https://cloud.githubusercontent.com/assets/2194396/6806336/fb4f0cf6-d23f-11e4-8e9e-3e537f84c2cf.png)

**Comment by bp323** [comment]
Not sure how much we'll be able to do about this since FullCalendar handles this.

**Comment by bp323** [comment]
After looking into this we won't be able to do much about it as there's no configuration for it except to turn it off completely.
