### ISSUE TITLE
Review merged issues

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#312]
#### Merged

- [x] https://github.com/CUL-DigitalServices/grasshopper-ui/pull/303
- [x] https://github.com/CUL-DigitalServices/grasshopper-ui/pull/308
- [x] https://github.com/CUL-DigitalServices/grasshopper-ui/pull/311

#### Unmerged

https://github.com/CUL-DigitalServices/grasshopper-ui/pull/306
https://github.com/CUL-DigitalServices/grasshopper-ui/pull/313
https://github.com/CUL-DigitalServices/grasshopper-ui/pull/314

**Comment by bp323** [comment]
Reviewed all issues, closing.
