### ISSUE TITLE
Improve Batch editor input field visibility

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#315]
* [x] Set the border for all input fields in the batch editor when active to #171717
* [x] If possible, it would be nice to increase the contrast for the placeholder texts a little bit too

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6919208/fb3d06d8-d7ac-11e4-88a6-5cf4f3e9187a.png)

**Comment by bp323** [comment]
This was fixed as part of https://github.com/CUL-DigitalServices/grasshopper-ui/pull/328. Closing
