### ISSUE TITLE
Add tooltip to series title inline edit

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#316]
When hovering over the series title, the cursor changes which is good, but there is no tooltip to give indication that you can edit. We should add a tooltip with the following copy:

"Click to edit the title of this series

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6919253/6c603aec-d7ad-11e4-8b4e-14d35e6a20e0.png)
"

**Comment by Coenego** [comment]
Fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/306
