### ISSUE TITLE
On any new event addition copy existing event metadata

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#317]
When adding new events to a series (via batch edit, Add new events, or Add new event buttons), if there are other events present with metadata, the new events should inherit the last previous existing event's metadata.

The base of the copy should be the last event which was already there before the addition.

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6919360/3315567c-d7ae-11e4-8baa-5660f1bf97ec.png)

**Comment by bp323** [comment]
I've done this on a per term basis in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/326.

**Comment by bp323** [comment]
This is now fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/326, closing.
