### ISSUE TITLE
Student UI: Missing borrow link icon bug

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#321]
This is on QA, so it might have been fixed in DEV already, but filing it just in case. Essentialy the borrow icon is missing for a borrowed series

![my_timetable_mar_26_ _apr_1__2015](https://cloud.githubusercontent.com/assets/117483/6925582/3911f2c2-d7d8-11e4-9558-0f7f7045b685.png)

**Comment by Coenego** [comment]
This is definitely fixed (and deployed on dev0)

**Comment by bp323** [comment]
Closing as this is fixed
