### ISSUE TITLE
Admin UI left side nav bugs

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#327]
This might be a regression too, seen this on QA:

![timetable_administration](https://cloud.githubusercontent.com/assets/117483/6926756/5b7f3880-d7e0-11e4-86f5-133a594ca1db.png)

**Comment by Coenego** [comment]
The white borders have been fixed (deployed on dev0)

**Comment by bp323** [comment]
Assigning to @Coenego to assess the remaining work

**Comment by bp323** [comment]
This seems to be fixed in latest master, closing
