### ISSUE TITLE
Investigate better handling of overflow events in month calendar view

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#335]
This should be a quick spike to see if we can improve the display of overflow events in month mode. Currently we are cropping them, which is not ideal.
 
Full calendar can do this, which might be worth investigating, opening a little popover displaying the full list of events per day:
![fullcalendar_io_js_fullcalendar-2_3_1_demos_basic-views_html](https://cloud.githubusercontent.com/assets/117483/6997127/237c82f6-dba7-11e4-96e2-5e893f7264f1.png)

The current (legacy) functionality is to adjust the day cells to display all events within a day:
![timetable](https://cloud.githubusercontent.com/assets/117483/6997136/8d7a1fb0-dba7-11e4-9f41-54aaea6e0a49.png)

Either of these are better that current solution, but we would need to be careful how any of these would interact with a print view.

**Comment by bp323** [comment]
This feels like a bug to me as we already have the first screenshot in place.

**Comment by bp323** [comment]
Closing as the plugin takes all of this out of our hands and there's not a whole lot we can do without rewriting its internals.
