### ISSUE TITLE
Admin UI: Implement module management

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#336]
Implement module management (rename & delete essentially) by adding a little cog icon dropdown for modules in the left side nav, when they are in open state.

The design can be found on GDrive:
https://drive.google.com/open?id=0B2lp5OAL6DPFYnVhaXc2aVVHTUE&authuser=0

**Items**
 * [x] Add cog icon dropdown for open modules in the side nav
 * [x] New series does exactly what the existing New series button does
 * [x] Borrow series does exactly what the existing Borrow button does
 * [x] Rename module brings up the rename module modal (almost identical to creation modal)
 * [x] Delete module brings up a delete modal with an extra confirmation step
 * [x] Delete module: Primary delete action should only be enabled when "DELETE" is present in the confirmation input field
 * [x] Delete primary action deletes the whole organisational unit, and every series which is inside it. All borrowed series are also removed, but not deleted (just as if you remove it from the module)

* [x] Stretch goal, only if all the above is present: If we can show aggregated information about how many inbound borrows are to the lecture seres within the module (just as we do when we are deleting a series) we could surface an aggregated view of that, but this is rock bottom priority, and only a nice to have.

**Comment by bp323** [comment]
This has been fixed and merged per https://github.com/CUL-DigitalServices/grasshopper-ui/pull/330
