### ISSUE TITLE
Student U: Improve borrow link tooltip 

### ISSUE THREAD

**Issue by oszkarnagy** [CUL-DigitalServices/grasshopper-ui#338]
* [x] Align tooltip position to icon
* [x] Include originating tripos AND part information

![my_timetable_apr_2_ _8__2015](https://cloud.githubusercontent.com/assets/117483/6997287/7ca4035c-dbae-11e4-9a52-bdf715706a32.png)

* [ ] Tangential: We should really try to fix the scroll bar issue, as this example shows how sloppy is it to have a scrollbar there, apart from interfering with adding series and modules to the calendar.

**Comment by bp323** [comment]
Assigning to @Coenego who's been working in the area

**Comment by Coenego** [comment]
Fixed in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/322
