### ISSUE TITLE
Timetable admin Add Event- module (List view and calendar view) is not displayed in Safari Browser 

### ISSUE THREAD

**Issue by ak883** [CUL-DigitalServices/grasshopper-ui#391]
Timetable admin Add Event- module (List view and calendar view) is not available in Safari Browser (version 5.1.7)- OS Windows 7 Professional

This is blocker ,stopping to carry further testing in Safari Browser

Attached Screen Shot

![module list -calander view](https://cloud.githubusercontent.com/assets/12182828/7566504/0d074c68-f7ef-11e4-9466-db9392e180a4.png)

**Comment by bp323** [comment]
Safari 5 is the latest for windows but seriously outdated. For this reason we won't support it.
