### ISSUE TITLE
Timetable Admin-FAQ link doesn’t respond in any browser  

### ISSUE THREAD

**Issue by ak883** [CUL-DigitalServices/grasshopper-ui#422]
Timetable Admin-FAQ link doesn’t respond in any browser  

![faq link](https://cloud.githubusercontent.com/assets/12182828/7745110/919422d6-ffa0-11e4-9004-7450db602f92.JPG)

**Comment by Coenego** [comment]
This is because there is no FAQ yet. Closing for now.
