### ISSUE TITLE
"Search triposes" field does not align with placeholder

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#440]
The cursor in the "Search triposes" field does not appear to be perfectly aligned with the placeholder text in the field.

![2bb802ea-04cb-11e5-82d0-59eeb0102834](https://cloud.githubusercontent.com/assets/2194396/7856727/3936f900-0523-11e5-8079-b4a53bfaff8c.png)

**Comment by bp323** [comment]
This doesn't seem to happen in any IE version or chrome. Playing around with padding or font-sizes doesn't seem to do much. Closing
