### ISSUE TITLE
Batch edit when creating a new series is broken

### ISSUE THREAD

**Issue by simong** [CUL-DigitalServices/grasshopper-ui#472]
I'm seeing this on both Firefox and Chrome.

Steps to reproduce:

1. Create a new series
2. Select Michaelmas
3. Check W1, W2 and W3

You end up with:
![](https://cldup.com/YFoNb_XsJp-3000x3000.png)

When clicking the trash icon next to the drop downs the weeks get deselected again.

There's an additional issue that the dates don't change in the event list when changing a day or hour

**Comment by bp323** [comment]
I cannot reproduce this on the latest UI. Various batch edit fixes have gone in towards the end of last week that seemed to have fixed this as well.
