### ISSUE TITLE
Moment deprecation warning

### ISSUE THREAD

**Issue by Coenego** [CUL-DigitalServices/grasshopper-ui#97]
When importing events, the following warning gets thrown:

`Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779`

**Comment by bp323** [comment]
Should this be moved to grasshopper?

**Comment by Coenego** [comment]
This is something we use to interact with Full Calendar, so this has to be handled in the UI.

**Comment by bp323** [comment]
This seems to be an issue in the back-end, closing.
